### ISSUE TITLE
Unable to download from ARTE.tv with youtube-dlg v1.8.3

### ISSUE THREAD

**Issue by switch6343** [oleksis/youtube-dl-gui#104]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer **honestly**
- Put an `x` into all the boxes [ ] relevant to your issue (like that [x])
- Use *Preview* tab to see how your issue will actually look like

### WARNING
All invalid issues will be rejected!!

---

### Before going further

- If your problem is a bug with **youtube-dl** or a request for new site support please report it [here](https://github.com/ytdl-org/youtube-dl/issues)

- Make sure you are using the *latest* **yt-dlg** version (Click the `Settings` icon and then `About` to view the current version)

- Make sure you are using the *latest* **youtube-dl** version (Click the `Settings` icon and then `Update` to update to the latest **youtube-dl** version)

- Make sure you searched the bugtracker for similar issues **including closed ones**

- Make sure to read the [FAQs](https://github.com/oleksis/youtube-dl-gui/blob/master/docs/faqs.md) file

  - [x] **I think** my problem is **NOT** with **youtube-dl**
  - [x] I've **verified** and **i assure** that I'm running yt-dlg **1.X.Y**
  - [x] **I assure** that i am using the latest version of **youtube-dl**
  - [x [Searched](https://github.com/oleksis/youtube-dl-gui/issues) bugtracker
  - [x] I've read the FAQs file

---

### What is the purpose of your *issue*?

- [ ] Bug report
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

Please remove any sections between (---) if they are not related to your issue

---

#### If the problem occurs when downloading a URL please provide the full verbose output as follows:

1. Restart **yt-dlg**
1. Go to `Options > Extra` tab
2. Enable **Debug youtube-dl**
3. Go to `Options > Advanced` tab and **Clear** your log content
4. Try to download the URL
5. Copy the **whole** log content and insert it between the ``` part below

```
2022-11-12 12:25:18,763-DEBUG-Worker_1-[debug] System config: []
2022-11-12 12:25:18,763-DEBUG-Worker_1-[debug] User config: []
2022-11-12 12:25:18,763-DEBUG-Worker_1-[debug] Custom config: []
2022-11-12 12:25:18,763-DEBUG-Worker_1-[debug] Command-line args: ['--newline', '-i', '-k', '-o', 'D:\\Videos\\ARTE.tv\\%(title)s.%(ext)s', '--ignore-config', '--hls-prefer-native', '--add-metadata', '--verbose', 'https://www.arte.tv/en/videos/095824-000-A/amalia-rodrigues-and-the-world-of-fado/ ']
2022-11-12 12:25:18,763-DEBUG-Worker_1-[debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252
2022-11-12 12:25:18,763-DEBUG-Worker_1-[debug] youtube-dl version 2021.12.17
2022-11-12 12:25:18,763-DEBUG-Worker_1-[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
2022-11-12 12:25:18,763-DEBUG-Worker_1-[debug] exe versions: none
2022-11-12 12:25:18,763-DEBUG-Worker_1-[debug] Proxy map: {}
2022-11-12 12:25:18,763-DEBUG-Worker_1-ERROR: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
2022-11-12 12:25:18,763-DEBUG-Worker_1-  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 634, in _request_webpage
2022-11-12 12:25:18,763-DEBUG-Worker_1-  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 2288, in urlopen
2022-11-12 12:25:18,763-DEBUG-Worker_1-  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
2022-11-12 12:25:18,763-DEBUG-Worker_1-  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
2022-11-12 12:25:18,763-DEBUG-Worker_1-  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
2022-11-12 12:25:18,763-DEBUG-Worker_1-  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
2022-11-12 12:25:18,772-DEBUG-Worker_1-  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default
2022-11-12 12:25:18,772-DEBUG-Worker_1-Child process exited with non-zero code: 1

```

#### What operating system do you use ?
Windows 10 Pro, updated to the latest version with all latest updates and patches.
I'm using youtube-dlg v1.8.3

#### List of actions to perform to reproduce the problem:

  1.  URL of ARTE.tv: https://www.arte.tv/en/videos/095824-000-A/amalia-rodrigues-and-the-world-of-fado/ 

 #### What is the expected behaviour ?
Error message. See error message above verbose

#### What happens instead ?
error message. See error message above verbose

---

### Feature request (request for a new functionality)

Please make sure that the requested feature is **NOT** already in the [TODO](https://github.com/oleksis/youtube-dl-gui/blob/master/TODO) list

- [x] I've **verified** and **i assure** that my requested feature is **NOT** in the TODO list

#### What operating system do you use ?
Windows 10 Pro, latest revision and with latest updates and patches

---

I noticed, that the error "Unable to download JSON metadata" a problem is that has been reported all over the place for at least 5 years. I haven't found any resolve. I don't understand why I am not able to download a Video from ARTE.tv using youtube-dlg v1.8.3.

**Comment by oleksis** [comment]
The GUI `yt-dlg` use CLI Backends like `youtube-dl` or `yt-dlp`.

Follow the [comment](https://github.com/oleksis/youtube-dl-gui/issues/82#issuecomment-1131067417) show how change the CLI Backend

> 1. Go Settings -> Options -> Extra
>   - Select `yt-dlp.exe` in CLI Backend, then Close
> 
> 2. Go Settings -> Update
>  - Wait until in the status bar show `Successfully downloaded CLI Backend.`

Doing the test `youtube-dl` the last version from **2021.12.17** show the error

```pwsh
➜ ./youtube-dl.exe --newline -i -o "C:\Users\user\Videos\%(title)s.%(ext)s" --ignore-config --hls-prefer-native "https://www.arte.tv/en/videos/095824-000-A/amalia-rodrigues-and-the-world-of-fado/"
[ArteTV] 095824-000-A: Downloading JSON metadata
ERROR: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

With `yt-dlp` version **2022.11.11** the download start without problem

```pwsh
➜ ./yt-dlp.exe --newline -i -o "C:\Users\user\Videos\%(title)s.%(ext)s" --ignore-config --hls-prefer-native "https://www.arte.tv/en/videos/095824-000-A/amalia-rodrigues-and-the-world-of-fado/"
[ArteTV] 095824-000-A: Downloading JSON metadata
[ArteTV] 095824-000-A: Downloading m3u8 information
[ArteTV] 095824-000-A: Downloading m3u8 information
[ArteTV] 095824-000-A: Downloading m3u8 information
[ArteTV] 095824-000-A: Downloading m3u8 information
[ArteTV] 095824-000-A: Downloading m3u8 information
[ArteTV] 095824-000-A: Downloading m3u8 information
[info] 095824-000-A: Downloading 1 format(s): VOEU-STE_ANG_-2328+VOEU-STE_ANG_-program_audio_0-VOEU
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 512
[download] Destination: C:\Users\user\Videos\Amália Rodrigues and the World of Fado.fVOEU-STE_ANG_-2328.mp4
[download]   0.0% of ~   9.43MiB at    1.59KiB/s ETA 01:40:58 (frag 0/512)
[download]   0.0% of ~   9.43MiB at    4.78KiB/s ETA 33:39 (frag 0/512)
[download]   0.1% of ~   9.43MiB at   11.16KiB/s ETA 14:24 (frag 0/512)
[download]   0.2% of ~   9.43MiB at   23.91KiB/s ETA 06:43 (frag 0/512)
[download]   0.2% of ~   9.43MiB at   30.07KiB/s ETA 05:20 (frag 0/512)
[download]   0.2% of ~   9.43MiB at   29.34KiB/s ETA 05:20 (frag 1/512)
[download]   0.0% of ~ 351.25MiB at    1.64KiB/s ETA 06:18:08 (frag 1/512)
[download]   0.0% of ~ 351.25MiB at    4.79KiB/s ETA 05:47:50 (frag 1/512)
[download]   0.0% of ~ 351.25MiB at   11.19KiB/s ETA 04:54:02 (frag 1/512)
[download]   0.0% of ~ 351.25MiB at   23.97KiB/s ETA 03:44:34 (frag 1/512)
[download]   0.0% of ~ 351.25MiB at   49.54KiB/s ETA 02:32:30 (frag 1/512)
...
```

**Comment by switch6343** [comment]
Thank you Oleksander for your testing.

I think I found out what the culprit is:
the youtube-dlg v1.8.3 **UPDATE FUNCTION** (under Settings) does NOT update to the latest yt-dlp v2022.11.11.

I started youtube-dlg v1.8.3 with Administrator rights, to ensure that the updating processes would succesfully finish, however to no avail. See here the contents of my logfile:

2022-11-13 05:06:08,926-DEBUG-Worker_1-[debug] System config: []
2022-11-13 05:06:08,926-DEBUG-Worker_1-[debug] User config: []
2022-11-13 05:06:08,926-DEBUG-Worker_1-[debug] Custom config: []
2022-11-13 05:06:08,926-DEBUG-Worker_1-[debug] Command-line args: ['--newline', '-i', '-k', '-o', 'D:\\Videos\\ARTE.tv\\%(title)s.%(ext)s', '-v', '--ignore-config', '--hls-prefer-native', '--add-metadata', 'https://www.arte.tv/en/videos/095824-000-A/amalia-rodrigues-and-the-world-of-fado/']
2022-11-13 05:06:08,926-DEBUG-Worker_1-[debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252
2022-11-13 05:06:08,926-DEBUG-Worker_1-[debug] **youtube-dl version 2021.12.17**
2022-11-13 05:06:08,926-DEBUG-Worker_1-[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
2022-11-13 05:06:08,926-DEBUG-Worker_1-[debug] exe versions: none
2022-11-13 05:06:08,926-DEBUG-Worker_1-[debug] Proxy map: {}
2022-11-13 05:06:08,926-DEBUG-Worker_1-ERROR: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
2022-11-13 05:06:08,926-DEBUG-Worker_1-  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 634, in _request_webpage
2022-11-13 05:06:08,926-DEBUG-Worker_1-  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 2288, in urlopen
2022-11-13 05:06:08,926-DEBUG-Worker_1-  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
2022-11-13 05:06:08,926-DEBUG-Worker_1-  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
2022-11-13 05:06:08,926-DEBUG-Worker_1-  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
2022-11-13 05:06:08,926-DEBUG-Worker_1-  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
2022-11-13 05:06:08,926-DEBUG-Worker_1-  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default
2022-11-13 05:06:08,926-DEBUG-Worker_1-Child process exited with non-zero code: 1
2022-11-13 05:25:08,418-DEBUG-Worker_1-[debug] System config: []
2022-11-13 05:25:08,418-DEBUG-Worker_1-[debug] User config: []
2022-11-13 05:25:08,418-DEBUG-Worker_1-[debug] Custom config: []
2022-11-13 05:25:08,418-DEBUG-Worker_1-[debug] Command-line args: ['--newline', '-i', '-k', '-o', 'D:\\Videos\\ARTE.tv\\%(title)s.%(ext)s', '-v', '--ignore-config', '--hls-prefer-native', '--add-metadata', 'https://www.arte.tv/en/videos/095824-000-A/amalia-rodrigues-and-the-world-of-fado/ ']
2022-11-13 05:25:08,418-DEBUG-Worker_1-[debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252
2022-11-13 05:25:08,418-DEBUG-Worker_1-[debug] youtube-dl version 2021.12.17
2022-11-13 05:25:08,418-DEBUG-Worker_1-[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
2022-11-13 05:25:08,418-DEBUG-Worker_1-[debug] exe versions: none
2022-11-13 05:25:08,418-DEBUG-Worker_1-[debug] Proxy map: {}
2022-11-13 05:25:08,418-DEBUG-Worker_1-ERROR: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
2022-11-13 05:25:08,418-DEBUG-Worker_1-  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 634, in _request_webpage
2022-11-13 05:25:08,418-DEBUG-Worker_1-  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 2288, in urlopen
2022-11-13 05:25:08,418-DEBUG-Worker_1-  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
2022-11-13 05:25:08,418-DEBUG-Worker_1-  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
2022-11-13 05:25:08,418-DEBUG-Worker_1-  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
2022-11-13 05:25:08,418-DEBUG-Worker_1-  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
2022-11-13 05:25:08,418-DEBUG-Worker_1-  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default
2022-11-13 05:25:08,418-DEBUG-Worker_1-Child process exited with non-zero code: 1

Would you please be so kind to analyze and as to why the Update Function in v1.8.3 does not properly update to the latest yt-dlp v2022.11.11?

I look forward hearing from you.

Kind regards,

switch6343

**Comment by oleksis** [comment]
All the logs you share above is related with `youtube-dl`.

Please try the Last release[ `yt-dlg` v.1.8.4](https://github.com/oleksis/youtube-dl-gui/releases/tag/v1.8.4) the exe or msi and the try the `Setting -> Update` function for update to the latest CLI Backend

Wait until the status bar in the GUI show `Successfully downloaded CLI Backend.`

**Comment by switch6343** [comment]
I uninstalled v1.8.3, rebooted and installed v1.8.4 MSI. Subsequently I pressed the UPDATE button and waited until the "successfully downloaded CLI Backend" was shown.

I again tried to download the documentary of Amália Rodrigues, however again to no avail. 

Here the contents of my log:

2022-11-13 20:15:34,188-DEBUG-Worker_1-[debug] System config: []
2022-11-13 20:15:34,204-DEBUG-Worker_1-[debug] User config: []
2022-11-13 20:15:34,204-DEBUG-Worker_1-[debug] Custom config: []
2022-11-13 20:15:34,204-DEBUG-Worker_1-[debug] Command-line args: ['--newline', '-i', '-k', '-o', 'D:\\Videos\\ARTE.tv\\%(title)s.%(ext)s', '-v', '--ignore-config', '--hls-prefer-native', '--add-metadata', 'https://www.arte.tv/en/videos/095824-000-A/amalia-rodrigues-and-the-world-of-fado/ ']
2022-11-13 20:15:34,204-DEBUG-Worker_1-[debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252
2022-11-13 20:15:34,204-DEBUG-Worker_1-[debug] youtube-dl version 2021.12.17
2022-11-13 20:15:34,204-DEBUG-Worker_1-[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
2022-11-13 20:15:34,204-DEBUG-Worker_1-[debug] exe versions: none
2022-11-13 20:15:34,204-DEBUG-Worker_1-[debug] Proxy map: {}
2022-11-13 20:15:34,204-DEBUG-Worker_1-ERROR: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
2022-11-13 20:15:34,204-DEBUG-Worker_1-  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 634, in _request_webpage
2022-11-13 20:15:34,204-DEBUG-Worker_1-  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 2288, in urlopen
2022-11-13 20:15:34,204-DEBUG-Worker_1-  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
2022-11-13 20:15:34,204-DEBUG-Worker_1-  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
2022-11-13 20:15:34,204-DEBUG-Worker_1-  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
2022-11-13 20:15:34,204-DEBUG-Worker_1-  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
2022-11-13 20:15:34,204-DEBUG-Worker_1-  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default
2022-11-13 20:15:34,204-DEBUG-Worker_1-Child process exited with non-zero code: 1

As you can see on line 7 "2022-11-13 20:15:34,204-DEBUG-Worker_1-[debug] youtube-dl version 2021.12.17" reference is made to **youtube-dl version 2021.12.17** and NOT the latest **youtube-dl version 2022.11.11**.

So, my conclusion is that the UPDATE function for some reason does NOT update to the latest youtube-dl version 2022.11.11.

Pls advise.

**Comment by oleksis** [comment]
Before hit the Update option follow [this steps](https://github.com/oleksis/youtube-dl-gui/issues/104#issuecomment-1312467243)

The latest version of `youtube-dl` is 2021.12.17 . The other CLI Backends is `yt-dlp` , make sure is selected in the options before Update function

**Comment by switch6343** [comment]
Oleksis, that did the trick: change from youtube-dl.exe to yt-dlp.exe. 

The documentary has been downloaded succesfully, I checked it. However TWO files were downloaded:

Amália Rodrigues and the World of Fado.fVOEU-STE_ANG_-2328.mp4 (filesize: 824302 KB)
Amália Rodrigues and the World of Fado.fVOEU-STE_ANG_-program_audio_0-VOEU.mp4 (filesize 49008 KB)

Here are the contents of the log:

022-11-14 02:58:10,349-DEBUG-Worker_1-[debug] Command-line config: ['--newline', '-i', '-k', '-o', 'D:\\Videos\\ARTE.tv\\%(title)s.%(ext)s', '-v', '--ignore-config', '--hls-prefer-native', '--add-metadata', 'https://www.arte.tv/en/videos/095824-000-A/amalia-rodrigues-and-the-world-of-fado/ ']
2022-11-14 02:58:10,349-DEBUG-Worker_1-[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out cp1252 (No ANSI), error cp1252 (No ANSI), screen cp1252 (No ANSI)
2022-11-14 02:58:10,349-DEBUG-Worker_1-[debug] yt-dlp version 2022.11.11 [8b64402] (win_exe)
2022-11-14 02:58:10,349-DEBUG-Worker_1-[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
2022-11-14 02:58:10,349-DEBUG-Worker_1-[debug] exe versions: none
2022-11-14 02:58:10,349-DEBUG-Worker_1-[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
2022-11-14 02:58:10,349-DEBUG-Worker_1-[debug] Proxy map: {}
2022-11-14 02:58:10,349-DEBUG-Worker_1-[debug] Loaded 1723 extractors
2022-11-14 02:58:10,349-DEBUG-Worker_1-[debug] [ArteTV] Extracting URL: https://www.arte.tv/en/videos/095824-000-A/amalia-rodrigues-and-the-world-of-fado/
2022-11-14 02:58:10,349-DEBUG-Worker_1-[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
2022-11-14 02:58:10,349-DEBUG-Worker_1-[debug] Default format spec: best/bestvideo+bestaudio
2022-11-14 02:58:10,349-DEBUG-Worker_1-WARNING: You have requested merging of multiple formats but ffmpeg is not installed. The formats won't be merged
2022-11-14 02:58:10,349-DEBUG-Worker_1-[debug] Invoking hlsnative downloader on "https://arte-cmafhls.akamaized.net/am/cmaf/095000/095800/095824-000-A/220914061944/medias/095824-000-A_v720.m3u8"
2022-11-14 02:58:10,349-DEBUG-Worker_1-[debug] File locking is not supported. Proceeding without locking
2022-11-14 02:58:10,349-DEBUG-Worker_1-[debug] Invoking hlsnative downloader on "https://arte-cmafhls.akamaized.net/am/cmaf/095000/095800/095824-000-A/220914061944/medias/095824-000-A_aud_VOEU.m3u8"
2022-11-14 02:58:10,349-DEBUG-Worker_1-ERROR: ffmpeg not found. Please install or provide the path using --ffmpeg-location
2022-11-14 02:58:10,349-DEBUG-Worker_1-Traceback (most recent call last):
2022-11-14 02:58:10,349-DEBUG-Worker_1-  File "yt_dlp\YoutubeDL.py", line 3414, in run_pp
2022-11-14 02:58:10,349-DEBUG-Worker_1-  File "yt_dlp\postprocessor\common.py", line 24, in run
2022-11-14 02:58:10,349-DEBUG-Worker_1-  File "yt_dlp\postprocessor\common.py", line 129, in wrapper
2022-11-14 02:58:10,349-DEBUG-Worker_1-  File "yt_dlp\postprocessor\ffmpeg.py", line 702, in run
2022-11-14 02:58:10,349-DEBUG-Worker_1-  File "yt_dlp\postprocessor\ffmpeg.py", line 323, in run_ffmpeg_multiple_files
2022-11-14 02:58:10,349-DEBUG-Worker_1-  File "yt_dlp\postprocessor\ffmpeg.py", line 328, in real_run_ffmpeg
2022-11-14 02:58:10,349-DEBUG-Worker_1-  File "yt_dlp\postprocessor\ffmpeg.py", line 231, in check_version
2022-11-14 02:58:10,349-DEBUG-Worker_1-yt_dlp.postprocessor.ffmpeg.FFmpegPostProcessorError: ffmpeg not found. Please install or provide the path using --ffmpeg-location
2022-11-14 02:58:10,349-DEBUG-Worker_1-Child process exited with non-zero code: 1

Please note that in the logfile, the file ffmpeg is flagged as missing. I already had noticed that, because in the original, now depreciated youtube-dlg v0.4.1 the following files were included:

ffmpeg.exe
ffprobe.exe

I can add the latest versions of ffmepg en ffprobe from https://www.gyan.dev/ffmpeg/builds/ to the path of the directory C:\Program Files\yt-dlg\yt-dlg\yt-dlg\ , but Is there any reason to have ffmpeg NOT included in the latest version of youtube-dlg v1.8.4?

Please advise.

**Comment by oleksis** [comment]
[FFmpeg need be installed](https://github.com/yt-dlp/yt-dlp#strongly-recommended) for the merging (post-processing) of some videos and audio 

Some reason:
- Size of the final installer
- You can update FFmpeg to the las t  version frequently or use other tools like `avconv`

**Comment by switch6343** [comment]
Oleksis, thanks!

I had enabled in Settings > Format > "Keep original files". I disabled this now, because this setting generates two more files, which for my purposes are not needed. However, I kept "Add metadate to file" as enabled, as set by me before. I also changed Audio quality from mid to high. 

I added the latest ffmpeg.exe file from https://www.gyan.dev/ffmpeg/builds/ to the path C:\Program Files\yt-dlg\yt-dlg\yt-dlg\. The whole process now works like a charm.

I also added ffprobe.exe. To be honest, I have no clue what his executable effectively does. What's the purpose of ffprobe? As I stated before, this executable file was included in youtube-dlg v1.8.4? Is this executable really needed?

Please advise.

I am glad you took on the baton to continue developing the youtube-dlg application. Very well done. Keep up the good work. 

Kind regards,

switch6343

**Comment by switch6343** [comment]
oleksis;

I stumbled over a very good publication on the subject of ffprobe, **ffprobe – Comprehensive Tutorial with 7 Examples**. See https://ottverse.com/ffprobe-comprehensive-tutorial-with-examples/

This publication convinced me that ffprobe.exe should be equally included together with ffmpeg.exe in the path where yt-dl is installed. As I stated before, the depreciated youtube-dlg v0.4.1 included ffmpeg as well as ffprobe.

I much appreciated your fast responses. oleksis, keep on keeping on. 

cheers

switch6343
