### ISSUE TITLE
Upgrade not working with Python packaging 23.0

### ISSUE THREAD

**Issue by Armag67** [oleksis/youtube-dl-gui#116]
Hello,

youtube-dl-gui 1.8.4 commit 23ccbc4 installation from AUR to my Manjaro box needs Python packaging < 23.0. I have packaging 23.0 in user mode and 21.3 in system-wide. I had to temporarily disable my user version of packaging for upgrading to this version of youtube-dl-gui...

**Comment by oleksis** [comment]
Packaging for different Distro with help from the Community. This issue will  reported to the maintainer packaging for the Arch distro.

**Comment by Armag67** [comment]
It's the same with packaging = 22.0 and commit 92025ea, here the traceback:
```
Traceback (most recent call last):
  File "/var/tmp/pamac-build-h2/youtube-dl-gui-git/src/youtube-dl-gui-git/setup.py", line 49, in <module>
    from setuptools import Command, setup
  File "/usr/lib/python3.10/site-packages/setuptools/__init__.py", line 247, in <module>
    monkey.patch_all()
  File "/usr/lib/python3.10/site-packages/setuptools/monkey.py", line 97, in patch_all
    patch_for_msvc_specialized_compiler()
  File "/usr/lib/python3.10/site-packages/setuptools/monkey.py", line 134, in patch_for_msvc_specialized_compiler
    msvc = import_module('setuptools.msvc')
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/lib/python3.10/site-packages/setuptools/msvc.py", line 24, in <module>
    from packaging.version import LegacyVersion
ImportError: cannot import name 'LegacyVersion' from 'packaging.version' (/home/h2/.local/lib/python3.10/site-packages/packaging/version.py)
```

**Comment by oleksis** [comment]
> ```bash
> ....
>   File "/usr/lib/python3.10/site-packages/setuptools/msvc.py", line 24, in <module>
>     from packaging.version import LegacyVersion
> ImportError: cannot import name 'LegacyVersion' from 'packaging.version' (/home/h2/.local/lib/python3.10/site-packages/packaging/version.py)
> ```

This logs look like is  `setuptools.msvc`  **ImportError** module-related error. **msvc** is  a Microsoft Visual C++ compiler
