### ISSUE TITLE
Fails to install via pip

### ISSUE THREAD

**Issue by RDKRACZ** [oleksis/youtube-dl-gui#136]
- Make sure to read the [FAQs](https://github.com/oleksis/youtube-dl-gui/blob/master/docs/faqs.md) file

  - [x] **I think** my problem is **NOT** with **youtube-dl**
  - [x] [Searched](https://github.com/oleksis/youtube-dl-gui/issues) bugtracker
  - [ ] ~~I've **verified** and **i assure** that I'm running yt-dlg **1.X.Y**~~ N/A
  - [ ] ~~**I assure** that i am using the latest version of **youtube-dl**~~ N/A
  - [ ] ~~I've read the FAQs file~~ It doesn't exists

---

### What is the purpose of your *issue*?

- [x] Bug report

---

### Bug report

```
[k0rr@fedora ~]$ pip install attrdict
Defaulting to user installation because normal site-packages is not writeable
Collecting attrdict
  Downloading attrdict-2.0.1-py2.py3-none-any.whl (9.9 kB)
Requirement already satisfied: six in /usr/lib/python3.10/site-packages (from attrdict) (1.16.0)
Installing collected packages: attrdict
Successfully installed attrdict-2.0.1
[k0rr@fedora ~]$ pip install yt-dlg
Defaulting to user installation because normal site-packages is not writeable
Collecting yt-dlg
  Using cached yt_dlg-1.8.5-py3-none-any.whl (231 kB)
Collecting pypubsub>=4.0.3 (from yt-dlg)
  Using cached Pypubsub-4.0.3-py3-none-any.whl (61 kB)
Collecting wxPython<=4.2.1a1,>=4.0.7.post2 (from yt-dlg)
  Using cached wxPython-4.2.0.tar.gz (71.0 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [19 lines of output]
      Traceback (most recent call last):
        File "/var/home/k0rr/.local/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/var/home/k0rr/.local/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/var/home/k0rr/.local/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-gdta0uup/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/tmp/pip-build-env-gdta0uup/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-gdta0uup/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 487, in run_setup
          super(_BuildMetaLegacyBackend,
        File "/tmp/pip-build-env-gdta0uup/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 27, in <module>
        File "/tmp/pip-install-1y08nxiu/wxpython_1522244ebc7e4a11b4834de5f4511995/buildtools/config.py", line 30, in <module>
          from attrdict import AttrDict
      ModuleNotFoundError: No module named 'attrdict'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

#### What operating system do you use?
Fedora
#### List of actions to perform to reproduce the problem:
`pip install yt-dlg`

#### What is the expected behaviour?
Successful installation

#### What happens instead?
As described above

**Comment by oleksis** [comment]
The problem is related to wxPython 4.2.0. Try install first wxPython 4.2.1 https://pypi.org/project/wxPython/

**Comment by oleksis** [comment]
Reed more this [issue](https://github.com/wxWidgets/Phoenix/issues/2398#issuecomment-1582594481)

**Comment by eddy-geek** [comment]
my workaround (before reading this issue) was:

```sh
sudo dnf install python3-wxpython4
```
