### ISSUE TITLE
Cannot run after install, No translation file found for domain: 'youtube_dl_gui'

### ISSUE THREAD

**Issue by ipkpjersi** [oleksis/youtube-dl-gui#15]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer **honestly**
- Put an `x` into all the boxes [ ] relevant to your issue (like that [x])
- Use *Preview* tab to see how your issue will actually look like

### WARNING
All invalid issues will be rejected!!

---

### Before going further

- If your problem is a bug with **youtube-dl** or a request for new site support please report it [here](https://github.com/rg3/youtube-dl/issues)

- Make sure you are using the *latest* **youtube-dlg** version (Click the `Settings` icon and then `About` to view the current version)

- Make sure you are using the *latest* **youtube-dl** version (Click the `Settings` icon and then `Update` to update to the latest **youtube-dl** version)

- Make sure you searched the bugtracker for similar issues **including closed ones**

- Make sure to read the [FAQs](https://github.com/oleksis/youtube-dl-gui/blob/master/docs/faqs.md) file

  - [x] **I think** my problem is **NOT** with **youtube-dl**
  - [x] I've **verified** and **i assure** that I'm running youtube-dlg **1.0.0**
  - [x] **I assure** that i am using the latest version of **youtube-dl**
  - [x] [Searched](https://github.com/oleksis/youtube-dl-gui/issues) bugtracker
  - [x] I've read the FAQs file

---

### What is the purpose of your *issue*?

- [x] Bug report
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

Please remove any sections between (---) if they are not related to your issue

---

### Bug report

I'm running into a bug when running youtube-dl-gui that I have built successfully with `sudo python3 setup.py install` and `sudo python3 setup.py pyinstaller`. I am using Ubuntu 18.04 LTS with Python 3. Basically, I cannot run the program, it has this stacktrace about a translation file:

```
Traceback (most recent call last):
  File "youtube_dl_gui/__init__.py", line 61, in <module>
  File "gettext.py", line 529, in translation
FileNotFoundError: [Errno 2] No translation file found for domain: 'youtube_dl_gui'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "youtube_dl_gui/__main__.py", line 34, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/usr/local/lib/python3.6/dist-packages/PyInstaller/loader/pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "youtube_dl_gui/__init__.py", line 66, in <module>
  File "gettext.py", line 529, in translation
FileNotFoundError: [Errno 2] No translation file found for domain: 'youtube_dl_gui'
[14978] Failed to execute script __main__
```
Here is the install log:
```
sudo python3 setup.py install
running install
running bdist_egg
running egg_info
writing youtube_dl_gui.egg-info/PKG-INFO
writing dependency_links to youtube_dl_gui.egg-info/dependency_links.txt
writing entry points to youtube_dl_gui.egg-info/entry_points.txt
writing top-level names to youtube_dl_gui.egg-info/top_level.txt
adding license file 'LICENSE' (matched pattern 'LICEN[CS]E*')
adding license file 'AUTHORS' (matched pattern 'AUTHORS*')
reading manifest file 'youtube_dl_gui.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files matching '*.mo' found under directory 'youtube_dl_gui/locale'
writing manifest file 'youtube_dl_gui.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/youtube_dl_gui
copying build/lib/youtube_dl_gui/downloadmanager.py -> build/bdist.linux-x86_64/egg/youtube_dl_gui
copying build/lib/youtube_dl_gui/info.py -> build/bdist.linux-x86_64/egg/youtube_dl_gui
copying build/lib/youtube_dl_gui/updatemanager.py -> build/bdist.linux-x86_64/egg/youtube_dl_gui
copying build/lib/youtube_dl_gui/optionsmanager.py -> build/bdist.linux-x86_64/egg/youtube_dl_gui
copying build/lib/youtube_dl_gui/formats.py -> build/bdist.linux-x86_64/egg/youtube_dl_gui
copying build/lib/youtube_dl_gui/parsers.py -> build/bdist.linux-x86_64/egg/youtube_dl_gui
copying build/lib/youtube_dl_gui/downloaders.py -> build/bdist.linux-x86_64/egg/youtube_dl_gui
copying build/lib/youtube_dl_gui/__main__.py -> build/bdist.linux-x86_64/egg/youtube_dl_gui
copying build/lib/youtube_dl_gui/widgets.py -> build/bdist.linux-x86_64/egg/youtube_dl_gui
copying build/lib/youtube_dl_gui/optionsframe.py -> build/bdist.linux-x86_64/egg/youtube_dl_gui
copying build/lib/youtube_dl_gui/logmanager.py -> build/bdist.linux-x86_64/egg/youtube_dl_gui
copying build/lib/youtube_dl_gui/flagart.py -> build/bdist.linux-x86_64/egg/youtube_dl_gui
copying build/lib/youtube_dl_gui/version.py -> build/bdist.linux-x86_64/egg/youtube_dl_gui
copying build/lib/youtube_dl_gui/utils.py -> build/bdist.linux-x86_64/egg/youtube_dl_gui
creating build/bdist.linux-x86_64/egg/youtube_dl_gui/data
creating build/bdist.linux-x86_64/egg/youtube_dl_gui/data/pixmaps
copying build/lib/youtube_dl_gui/data/pixmaps/stop_32px.png -> build/bdist.linux-x86_64/egg/youtube_dl_gui/data/pixmaps
copying build/lib/youtube_dl_gui/data/pixmaps/reload_32px.png -> build/bdist.linux-x86_64/egg/youtube_dl_gui/data/pixmaps
copying build/lib/youtube_dl_gui/data/pixmaps/settings_20px.png -> build/bdist.linux-x86_64/egg/youtube_dl_gui/data/pixmaps
copying build/lib/youtube_dl_gui/data/pixmaps/youtube-dl-gui.png -> build/bdist.linux-x86_64/egg/youtube_dl_gui/data/pixmaps
copying build/lib/youtube_dl_gui/data/pixmaps/folder_32px.png -> build/bdist.linux-x86_64/egg/youtube_dl_gui/data/pixmaps
copying build/lib/youtube_dl_gui/data/pixmaps/play_arrow_32px.png -> build/bdist.linux-x86_64/egg/youtube_dl_gui/data/pixmaps
copying build/lib/youtube_dl_gui/data/pixmaps/arrow_up_32px.png -> build/bdist.linux-x86_64/egg/youtube_dl_gui/data/pixmaps
copying build/lib/youtube_dl_gui/data/pixmaps/camera_32px.png -> build/bdist.linux-x86_64/egg/youtube_dl_gui/data/pixmaps
copying build/lib/youtube_dl_gui/data/pixmaps/pause_32px.png -> build/bdist.linux-x86_64/egg/youtube_dl_gui/data/pixmaps
copying build/lib/youtube_dl_gui/data/pixmaps/delete_32px.png -> build/bdist.linux-x86_64/egg/youtube_dl_gui/data/pixmaps
copying build/lib/youtube_dl_gui/data/pixmaps/cloud_download_32px.png -> build/bdist.linux-x86_64/egg/youtube_dl_gui/data/pixmaps
copying build/lib/youtube_dl_gui/data/pixmaps/arrow_down_32px.png -> build/bdist.linux-x86_64/egg/youtube_dl_gui/data/pixmaps
copying build/lib/youtube_dl_gui/__init__.py -> build/bdist.linux-x86_64/egg/youtube_dl_gui
copying build/lib/youtube_dl_gui/mainframe.py -> build/bdist.linux-x86_64/egg/youtube_dl_gui
byte-compiling build/bdist.linux-x86_64/egg/youtube_dl_gui/downloadmanager.py to downloadmanager.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/youtube_dl_gui/info.py to info.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/youtube_dl_gui/updatemanager.py to updatemanager.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/youtube_dl_gui/optionsmanager.py to optionsmanager.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/youtube_dl_gui/formats.py to formats.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/youtube_dl_gui/parsers.py to parsers.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/youtube_dl_gui/downloaders.py to downloaders.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/youtube_dl_gui/__main__.py to __main__.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/youtube_dl_gui/widgets.py to widgets.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/youtube_dl_gui/optionsframe.py to optionsframe.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/youtube_dl_gui/logmanager.py to logmanager.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/youtube_dl_gui/flagart.py to flagart.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/youtube_dl_gui/version.py to version.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/youtube_dl_gui/utils.py to utils.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/youtube_dl_gui/__init__.py to __init__.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/youtube_dl_gui/mainframe.py to mainframe.cpython-36.pyc
installing package data to build/bdist.linux-x86_64/egg
running install_data
creating build/bdist.linux-x86_64/egg/share
creating build/bdist.linux-x86_64/egg/share/icons
creating build/bdist.linux-x86_64/egg/share/icons/hicolor
creating build/bdist.linux-x86_64/egg/share/icons/hicolor/48x48
creating build/bdist.linux-x86_64/egg/share/icons/hicolor/48x48/apps
copying youtube_dl_gui/data/icons/hicolor/48x48/apps/youtube-dl-gui.png -> build/bdist.linux-x86_64/egg/share/icons/hicolor/48x48/apps
creating build/bdist.linux-x86_64/egg/share/icons/hicolor/16x16
creating build/bdist.linux-x86_64/egg/share/icons/hicolor/16x16/apps
copying youtube_dl_gui/data/icons/hicolor/16x16/apps/youtube-dl-gui.png -> build/bdist.linux-x86_64/egg/share/icons/hicolor/16x16/apps
creating build/bdist.linux-x86_64/egg/share/icons/hicolor/128x128
creating build/bdist.linux-x86_64/egg/share/icons/hicolor/128x128/apps
copying youtube_dl_gui/data/icons/hicolor/128x128/apps/youtube-dl-gui.png -> build/bdist.linux-x86_64/egg/share/icons/hicolor/128x128/apps
creating build/bdist.linux-x86_64/egg/share/icons/hicolor/64x64
creating build/bdist.linux-x86_64/egg/share/icons/hicolor/64x64/apps
copying youtube_dl_gui/data/icons/hicolor/64x64/apps/youtube-dl-gui.png -> build/bdist.linux-x86_64/egg/share/icons/hicolor/64x64/apps
creating build/bdist.linux-x86_64/egg/share/icons/hicolor/32x32
creating build/bdist.linux-x86_64/egg/share/icons/hicolor/32x32/apps
copying youtube_dl_gui/data/icons/hicolor/32x32/apps/youtube-dl-gui.png -> build/bdist.linux-x86_64/egg/share/icons/hicolor/32x32/apps
creating build/bdist.linux-x86_64/egg/share/icons/hicolor/256x256
creating build/bdist.linux-x86_64/egg/share/icons/hicolor/256x256/apps
copying youtube_dl_gui/data/icons/hicolor/256x256/apps/youtube-dl-gui.png -> build/bdist.linux-x86_64/egg/share/icons/hicolor/256x256/apps
creating build/bdist.linux-x86_64/egg/share/pixmaps
copying youtube_dl_gui/data/pixmaps/youtube-dl-gui.png -> build/bdist.linux-x86_64/egg/share/pixmaps
creating build/bdist.linux-x86_64/egg/share/man
creating build/bdist.linux-x86_64/egg/share/man/man1
copying youtube-dl-gui.1 -> build/bdist.linux-x86_64/egg/share/man/man1
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying youtube_dl_gui.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying youtube_dl_gui.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying youtube_dl_gui.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying youtube_dl_gui.egg-info/entry_points.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying youtube_dl_gui.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
youtube_dl_gui.__pycache__.__main__.cpython-36: module references __file__
youtube_dl_gui.__pycache__.utils.cpython-36: module references __file__
creating 'dist/youtube_dl_gui-1.2.0-py3.6.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing youtube_dl_gui-1.2.0-py3.6.egg
removing '/usr/local/lib/python3.6/dist-packages/youtube_dl_gui-1.2.0-py3.6.egg' (and everything under it)
creating /usr/local/lib/python3.6/dist-packages/youtube_dl_gui-1.2.0-py3.6.egg
Extracting youtube_dl_gui-1.2.0-py3.6.egg to /usr/local/lib/python3.6/dist-packages
youtube-dl-gui 1.2.0 is already the active version in easy-install.pth
Installing youtube-dl-gui script to /usr/local/bin

Installed /usr/local/lib/python3.6/dist-packages/youtube_dl_gui-1.2.0-py3.6.egg
Processing dependencies for youtube-dl-gui==1.2.0
Finished processing dependencies for youtube-dl-gui==1.2.0
```

Here is the pyinstaller log: 
![](https://i.imgur.com/B3HjbKi.png)

**Comment by oleksis** [comment]
Hi @ipkpjersi 
Can check this line in the [Makefile]( https://github.com/oleksis/youtube-dl-gui/blob/147baa67bf9f09f53a45b7f57b50345b0a52c780/Makefile#L53) before run `install` and `pyinstaller` You need run for make the translation and compile the **\*.mo** in your case run first :

```bash
python3 setup.py build_trans
```
Then install or create the binary 
```bash
python3 setup.py install
```

**Comment by ipkpjersi** [comment]
Yep that did the trick, thank you for your very quick response! :+1:
