### ISSUE TITLE
Doesn't install on macOS 14.4

### ISSUE THREAD

**Issue by CaliMiller** [oleksis/youtube-dl-gui#179]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer **honestly**
- Put an `x` into all the boxes [ ] relevant to your issue (like that [x])
- Use *Preview* tab to see how your issue will actually look like

### WARNING
All invalid issues will be rejected!!

---

### Before going further

- If your problem is a bug with **youtube-dl** or a request for new site support please report it [here](https://github.com/ytdl-org/youtube-dl/issues)

- Make sure you are using the *latest* **yt-dlg** version (Click the `Settings` icon and then `About` to view the current version)

- Make sure you are using the *latest* **youtube-dl** version (Click the `Settings` icon and then `Update` to update to the latest **youtube-dl** version)

- Make sure you searched the bugtracker for similar issues **including closed ones**

- Make sure to read the [FAQs](https://github.com/oleksis/youtube-dl-gui/blob/master/docs/faqs.md) file

  - [ ] **I think** my problem is **NOT** with **youtube-dl**
  - [ ] I've **verified** and **i assure** that I'm running yt-dlg **1.X.Y**
  - [ ] **I assure** that i am using the latest version of **youtube-dl**
  - [X] [Searched](https://github.com/oleksis/youtube-dl-gui/issues) bugtracker
  - [ ] I've read the FAQs file

---

### What is the purpose of your *issue*?

- [X] Bug report
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

Please remove any sections between (---) if they are not related to your issue

---

#### If the problem occurs when downloading a URL please provide the full verbose output as follows:

1. Restart **yt-dlg**
1. Go to `Options > Extra` tab
2. Enable **Debug youtube-dl**
3. Go to `Options > Advanced` tab and **Clear** your log content
4. Try to download the URL
5. Copy the **whole** log content and insert it between the ``` part below

```



python-build: use openssl@1.1 from homebrew
python-build: use readline from homebrew
Downloading Python-3.10.6.tar.xz...
-> https://www.python.org/ftp/python/3.10.6/Python-3.10.6.tar.xz
Installing Python-3.10.6...
python-build: use readline from homebrew
python-build: use zlib from xcode sdk
Installed Python-3.10.6 to /Volumes/Mac5TB/Users/raddykewl/.pyenv/versions/3.10.6
pyenv: shell integration not enabled. Run `pyenv init' for instructions.
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements/requirements.in'
Collecting yt-dlg
  Obtaining dependency information for yt-dlg from https://files.pythonhosted.org/packages/1a/cb/19632dc8ec4dbd72543cad0cdc1037c4521ed281d5c48f931c7580768a5e/yt_dlg-1.8.5-py3-none-any.whl.metadata
  Downloading yt_dlg-1.8.5-py3-none-any.whl.metadata (15 kB)
Collecting pypubsub>=4.0.3 (from yt-dlg)
  Obtaining dependency information for pypubsub>=4.0.3 from https://files.pythonhosted.org/packages/1a/41/a0aceb552d8ec63bb1e8223d130f9dd0f736470036d75d708183b104a2cb/Pypubsub-4.0.3-py3-none-any.whl.metadata
  Downloading Pypubsub-4.0.3-py3-none-any.whl.metadata (2.2 kB)
Collecting wxPython<=4.2.1a1,>=4.0.7.post2 (from yt-dlg)
  Downloading wxPython-4.2.0.tar.gz (71.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 71.0/71.0 MB 3.5 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/gl/m3cc6hlx3_35s5sz2qs7kw140000gn/T/pip-install-0vupikib/wxpython_0c1f7a3e04b04d6dbfcff8ccd067dedb/setup.py", line 27, in <module>
          from buildtools.config import Config, msg, opj, runcmd, canGetSOName, getSOName
        File "/private/var/folders/gl/m3cc6hlx3_35s5sz2qs7kw140000gn/T/pip-install-0vupikib/wxpython_0c1f7a3e04b04d6dbfcff8ccd067dedb/buildtools/config.py", line 30, in <module>
          from attrdict import AttrDict
      ModuleNotFoundError: No module named 'attrdict'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
zsh: command not found: yt-dlg






```

#### What operating system do you use ?

macOS Sonoma 14.4

#### List of actions to perform to reproduce the problem:

PYTHON_CONFIGURE_OPTS="--enable-framework" pyenv install 3.10.6
pyenv shell 3.10.6
python -m pip install -r requirements/requirements.in
pip install yt-dlg
yt-dlg

#### What is the expected behaviour ?

Installing yt-dlg

#### What happens instead ?

Error messages (see log above)

**Comment by romanr** [comment]
Same here, tried pip3, venv, pipx, all give same error
>       ModuleNotFoundError: No module named 'attrdict'

**Comment by romanr** [comment]
Caused by this https://github.com/wxWidgets/Phoenix/issues/2296
