### ISSUE TITLE
Yt-dlg only downloads youtube videos as .webm files, or before reinstalling yt-dlg, as .m4a files, even when choosing the .mp3 file type option

### ISSUE THREAD

**Issue by sfilie03** [oleksis/youtube-dl-gui#192]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer **honestly**
- Put an `x` into all the boxes [ ] relevant to your issue (like that [x])
- Use *Preview* tab to see how your issue will actually look like

### WARNING
All invalid issues will be rejected!!

---

### Before going further

- If your problem is a bug with **youtube-dl** or a request for new site support please report it [here](https://github.com/ytdl-org/youtube-dl/issues)

- Make sure you are using the *latest* **yt-dlg** version (Click the `Settings` icon and then `About` to view the current version)

- Make sure you are using the *latest* **youtube-dl** version (Click the `Settings` icon and then `Update` to update to the latest **youtube-dl** version)

- Make sure you searched the bugtracker for similar issues **including closed ones**

- Make sure to read the [FAQs](https://github.com/oleksis/youtube-dl-gui/blob/master/docs/faqs.md) file

  - [x] **I think** my problem is **NOT** with **youtube-dl**
  - [x] I've **verified** and **i assure** that I'm running yt-dlg **1.X.Y**
  - [x] **I assure** that i am using the latest version of **youtube-dl**
  - [x] [Searched](https://github.com/oleksis/youtube-dl-gui/issues) bugtracker
  - [x] I've read the FAQs file

---

### What is the purpose of your *issue*?

- [ ] Bug report
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

Please remove any sections between (---) if they are not related to your issue

---

#### If the problem occurs when downloading a URL please provide the full verbose output as follows:

1. Restart **yt-dlg**
1. Go to `Options > Extra` tab
2. Enable **Debug youtube-dl**
3. Go to `Options > Advanced` tab and **Clear** your log content
4. Try to download the URL
5. Copy the **whole** log content and insert it between the ``` part below

```
2024-11-16 13:43:13,442-DEBUG-Worker_1-[debug] Command-line config: ['--newline', '-i', '-o', 'C:\\Users\\User\\Downloads\\%(title)s.%(ext)s', '-x', '--audio-format', 'mp3', '-v', '--ignore-config', '--hls-prefer-native', 'https://www.youtube.com/watch?v=Zi_XLOBDo_Y']
2024-11-16 13:43:13,442-DEBUG-Worker_1-[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out cp1252 (No VT), error cp1252 (No VT), screen cp1252 (No VT)
2024-11-16 13:43:13,442-DEBUG-Worker_1-[debug] yt-dlp version stable@2024.11.04 from yt-dlp/yt-dlp [197d0b03b] (win_exe)
2024-11-16 13:43:13,442-DEBUG-Worker_1-[debug] Python 3.10.11 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1t  7 Feb 2023)
2024-11-16 13:43:13,446-DEBUG-Worker_1-[debug] exe versions: none
2024-11-16 13:43:13,446-DEBUG-Worker_1-[debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2024.08.30, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.40.1, urllib3-2.2.3, websockets-13.1
2024-11-16 13:43:13,446-DEBUG-Worker_1-[debug] Proxy map: {}
2024-11-16 13:43:13,446-DEBUG-Worker_1-[debug] Request Handlers: urllib, requests, websockets, curl_cffi
2024-11-16 13:43:13,446-DEBUG-Worker_1-[debug] Loaded 1838 extractors
2024-11-16 13:43:13,446-DEBUG-Worker_1-[debug] [youtube] Extracting signature function js_0ccfa671_105
2024-11-16 13:43:13,446-DEBUG-Worker_1-[debug] Loading youtube-sigfuncs.js_0ccfa671_105 from cache
2024-11-16 13:43:13,446-DEBUG-Worker_1-[debug] Loading youtube-nsig.0ccfa671 from cache
2024-11-16 13:43:13,450-DEBUG-Worker_1-[debug] [youtube] Decrypted nsig GTO-geSm1hOzEnC => eEhmXkOtdDvleQ
2024-11-16 13:43:13,450-DEBUG-Worker_1-[debug] Loading youtube-nsig.0ccfa671 from cache
2024-11-16 13:43:13,450-DEBUG-Worker_1-[debug] [youtube] Decrypted nsig tKa9PgVlhXzbNzm => d95wDJY6E6exdw
2024-11-16 13:43:13,450-DEBUG-Worker_1-[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec, channels, acodec, lang, proto
2024-11-16 13:43:13,450-DEBUG-Worker_1-[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec, channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
2024-11-16 13:43:13,450-DEBUG-Worker_1-[debug] Invoking http downloader on "https://rr4---sn-gvbxgn-tvf6.googlevideo.com/videoplayback?expire=1731804190&ei=vuc4Z8fuKcGkir4PxO6JmAw&ip=2607%3Afea8%3Ae366%3A1000%3Ae850%3Abc8e%3A8a90%3A2fb3&id=o-ALMJTlxyDvfhZJeBn5-aW6P-fDxbvIvnlzwAv_-i-fxX&itag=251&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&met=1731782590%2C&mh=yF&mm=31%2C29&mn=sn-gvbxgn-tvf6%2Csn-gvbxgn-tt1ee&ms=au%2Crdu&mv=m&mvi=4&pl=41&rms=au%2Cau&gcr=ca&initcwndbps=1748750&spc=qtApAahtpOqU8raQ85Ob7-njmorWRFCi_PWE2qiGd09ikUc&vprv=1&svpuc=1&mime=audio%2Fwebm&rqh=1&gir=yes&clen=4934666&dur=295.861&lmt=1700456040073261&mt=1731782244&fvip=4&keepalive=yes&fexp=51299154%2C51312688%2C51326932&c=IOS&txp=4532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cgcr%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRQIhANWNH5eu6D-wx9zooHU2VPt06WQVfZ48eOLjKFt8NUaaAiBvXsXtowj3ohu6feSYIkrfLzxoo34DAJDCzDk1zXT3Bw%3D%3D&lsparams=met%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Crms%2Cinitcwndbps&lsig=AGluJ3MwRQIhAO869JY1Td5Q9peNbrX_d1pbRLcBDJ8Eh6w0LUOf-5k2AiA0zBH55u0GpHprTcqXWcCYQjF8vJQqMmDN6EjpkgvdLQ%3D%3D"
2024-11-16 13:43:13,450-DEBUG-Worker_1-[debug] File locking is not supported. Proceeding without locking
2024-11-16 13:43:13,450-DEBUG-Worker_1-ERROR: ffprobe and ffmpeg not found. Please install or provide the path using --ffmpeg-location
2024-11-16 13:43:13,450-DEBUG-Worker_1-Traceback (most recent call last):
2024-11-16 13:43:13,450-DEBUG-Worker_1-  File "yt_dlp\YoutubeDL.py", line 3701, in run_pp
2024-11-16 13:43:13,450-DEBUG-Worker_1-  File "yt_dlp\postprocessor\common.py", line 23, in run
2024-11-16 13:43:13,454-DEBUG-Worker_1-  File "yt_dlp\postprocessor\common.py", line 128, in wrapper
2024-11-16 13:43:13,454-DEBUG-Worker_1-  File "yt_dlp\postprocessor\ffmpeg.py", line 494, in run
2024-11-16 13:43:13,454-DEBUG-Worker_1-  File "yt_dlp\postprocessor\ffmpeg.py", line 242, in get_audio_codec
2024-11-16 13:43:13,454-DEBUG-Worker_1-yt_dlp.utils.PostProcessingError: ffprobe and ffmpeg not found. Please install or provide the path using --ffmpeg-location
2024-11-16 13:43:13,454-DEBUG-Worker_1-Child process exited with non-zero code: 1
```

#### What operating system do you use ?
Microsoft Windows 10 Pro 22H2 19045.5131

#### List of actions to perform to reproduce the problem:

  1. Open yt-dlg.exe.
  2. Add a URL to download an .mp3 file from a youtube video.
  3. Close yt-dlg.exe.

#### What is the expected behaviour ?
Yt-dlg should download a youtube URL as an .mp3 file if that's the selected download file type, and save it to the computer.

#### What happens instead ?
Yt-dlg downloads and saves a youtube URL as a .webm file, or as .m4a files if I put "--audio-format mp3 --audio-quality 128 -f 'bestaudio[asr=44100]'" in the options, extra settings, even though I selected .mp3 files as the download file type.

---

### Feature request (request for a new functionality)

Please make sure that the requested feature is **NOT** already in the [TODO](https://github.com/oleksis/youtube-dl-gui/blob/master/TODO) list

- [x] I've **verified** and **i assure** that my requested feature is **NOT** in the TODO list

#### What operating system do you use ?
Microsoft Windows 10 Pro 22H2 19045.5131

---

Yt-dlg one one of my computers works properly, and downloads files in the correct selected file type, however on another computer, it doesn't download youtube URLs as .mp3 files when that's the selected file type. It only saves them as .webm files, or as .m4a files if I put "--audio-format mp3 --audio-quality 128 -f 'bestaudio[asr=44100]'" in the options, extra settings, even after using the update option. Also, the file status says "error" after downloading the file. I'm using yt-dlg 1.8.5, installed in the default installation directory, and have already selected the update option, and chosen the download file type as .mp3 files. I've already tried reinstalling yt-dlg, but it has the same issue. How do I get it to download .mp3 files, especially with custom audio settings? Is there a way to fix that?

**Comment by EdisAganovic** [comment]
"ffprobe and ffmpeg not found."

https://www.ffmpeg.org/download.html
