### ISSUE TITLE
youtube-dl-gui-git will not install

### ISSUE THREAD

**Issue by Locutus64** [oleksis/youtube-dl-gui#73]
I'm running Garuda Dragonized Blackarch KDE and when I try to install youtube-dl-gui-git I get the below. Any idea on how to fix this?

```
Preparing...
Cloning youtube-dl-gui-git build files...
Generating youtube-dl-gui-git information...
Checking youtube-dl-gui-git dependencies...
Resolving dependencies...
Checking inter-conflicts...

Building youtube-dl-gui-git...
==> Making package: youtube-dl-gui-git 1.8.2.r2.gfe117a8-1 (Mon 13 Dec 2021 09:17:14 AM PST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Updating youtube-dl-gui-git git repo...
Fetching origin
From https://github.com/oleksis/youtube-dl-gui
   fe117a8..f5ef460  master     -> master
  -> Found youtube-dl-gui.desktop
==> Validating source files with sha256sums...
    youtube-dl-gui-git ... Skipped
    youtube-dl-gui.desktop ... Passed
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Creating working copy of youtube-dl-gui-git git repo...
Cloning into 'youtube-dl-gui-git'...
done.
==> Starting pkgver()...
==> Updated version: youtube-dl-gui-git 1.8.2.r5.gf5ef460-1
==> Removing existing $pkgdir/ directory...
==> Entering fakeroot environment...
==> Starting package()...
/var/tmp/pamac-build-locutus/youtube-dl-gui-git/src/youtube-dl-gui-git/setup.py:46: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  from distutils import log
running build_trans
Traceback (most recent call last):
  File "/var/tmp/pamac-build-locutus/youtube-dl-gui-git/src/youtube-dl-gui-git/setup.py", line 315, in <module>
    setup(
  File "/usr/lib/python3.10/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.10/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.10/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.10/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/var/tmp/pamac-build-locutus/youtube-dl-gui-git/src/youtube-dl-gui-git/setup.py", line 132, in run
    import polib
ModuleNotFoundError: No module named 'polib'
==> ERROR: A failure occurred in package().
    Aborting...
```

**Comment by oleksis** [comment]
I will like know the origins for the packman package and check the specifics file include the build requirements libraries for Python 3 like polib for translations.

My advice is contact the maintainer for the Arch package or install using pip:

`pip install -U yt-dlg`

**Comment by Locutus64** [comment]
Sorry for not getting back to you sooner but a couple of things came up. I just did a fresh install of Manjaro, installed pip, used the above command, then attempted the GUI version again and it installed without issue. Thanks very much appreciated.
