### ISSUE TITLE
WARNING: [youtube] nsig extraction failed

### ISSUE THREAD

**Issue by Akhilesh-T** [oleksis/youtube-dl-gui#79]
- [X] **I think** my problem is **NOT** with **youtube-dl**
  - [X] I've **verified** and **i assure** that I'm running yt-dlg **1.8.2**
  - [X] **I assure** that i am using the latest version of **youtube-dl**
  - [X] [Searched](https://github.com/oleksis/youtube-dl-gui/issues) bugtracker
  - [x] I've read the FAQs file

---

### What is the purpose of your *issue*?

- [ ] Bug report
- [ ] Feature request (request for a new functionality)
- [X] Question
- [ ] Other

---
### Log
```
2022-02-04 10:02:52,887-DEBUG-Worker_1-WARNING: [youtube] nsig extraction failed: You may experience throttling for some formats
2022-02-04 10:02:52,942-DEBUG-Worker_1-n = mS2yC3cq9qUIZnnA9 ; player = https://www.youtube.com/s/player/0cd11746/player_ias.vflset/en_US/base.js
2022-02-04 10:02:52,942-DEBUG-Worker_1-gxQ7PPzaVgo: Traceback (most recent call last):
2022-02-04 10:02:52,943-DEBUG-Worker_1-  File "yt_dlp\extractor\youtube.py", line 2412, in _decrypt_nsig
2022-02-04 10:02:52,943-DEBUG-Worker_1-  File "yt_dlp\extractor\youtube.py", line 2433, in _extract_n_function
2022-02-04 10:02:52,943-DEBUG-Worker_1-  File "yt_dlp\extractor\youtube.py", line 2421, in _extract_n_function_name
2022-02-04 10:02:52,943-DEBUG-Worker_1-  File "yt_dlp\extractor\common.py", line 1186, in _search_regex
2022-02-04 10:02:52,943-DEBUG-Worker_1-yt_dlp.utils.RegexNotFoundError: Unable to extract Initial JS player n function name; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
2022-02-04 10:02:52,944-DEBUG-Worker_1- (caused by RegexNotFoundError('Unable to extract Initial JS player n function name; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.')); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.

```

#### What operating system do you use ?
Windows 10
#### List of actions to perform to reproduce the problem:

  1. Download video

#### What is the expected behaviour ?
The download should end with a _Finish_ status

#### What happens instead ?
The download ends with a _Warning_ status

---

_This is happening only for specific videos, and the videos play correctly even when the app displays this warning._

**Comment by oleksis** [comment]
Which version of `yt-dlp` using? Few hours ago they release the fix versión `yt-dlp` [version __2022.02.04__](https://github.com/yt-dlp/yt-dlp/releases/tag/2022.02.04)

**Comment by Akhilesh-T** [comment]
Thanks. The latest `yt-dlp` update seems to have fixed this,
